name: Jobs CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: CODIFICAÇÃO
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 5
        done

    - name: Run script
      working-directory: CODIFICAÇÃO
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        DATABASE_URL: mysql+pymysql://root:root@127.0.0.1:3306/testdb
      run: python run.py
