name: Jobs CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: List files in the repository
      run: ls -R

    - name: Change to repository directory
      run: cd PI_4SEM_2024/CODIFICAÇÃO 

    - name: List files in the repository
      run: ls -R
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      run: python run.py
